/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/group-saving-onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/saving-plan`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/fin-manage` | `/fin-manage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rewards` | `/rewards`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/group-saving-onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/saving-plan`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/fin-manage` | `/fin-manage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rewards` | `/rewards`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/group-saving-onboarding${`?${string}` | `#${string}` | ''}` | `/saving-plan${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/fin-manage${`?${string}` | `#${string}` | ''}` | `/fin-manage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/me${`?${string}` | `#${string}` | ''}` | `/me${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rewards${`?${string}` | `#${string}` | ''}` | `/rewards${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/group-saving-onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/saving-plan`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/fin-manage` | `/fin-manage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rewards` | `/rewards`; params?: Router.UnknownInputParams; };
    }
  }
}
